# Generated by Django 4.1.1 on 2023-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ofc_discom", models.CharField(blank=True, max_length=300, null=True)),
                ("ofc_zone", models.CharField(blank=True, max_length=300, null=True)),
                ("ofc_circle", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "ofc_division",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "ofc_sub_div_code",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "ofc_subdivision",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "ofc_section",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("mr_unit", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "bl_area_code",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "bl_agnc_type",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "bl_agnc_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("mr_id", models.CharField(blank=True, max_length=300, null=True)),
                ("mr_ph_no", models.CharField(blank=True, max_length=300, null=True)),
                ("cons_ac_no", models.CharField(blank=True, max_length=300, null=True)),
                ("cons_name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "cons_address",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("cons_ph_no", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "cons_vill_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "cons_fdr_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("con_dtc", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "con_trf_cat",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "con_mtr_sl_no",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "con_mtr_phs",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "rdng_inc_deci",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "rdng_req_val",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("prev_rdng", models.CharField(blank=True, max_length=300, null=True)),
                ("prev_md", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "prev_pf_rdng",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "prev_rdng_date",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "prev_bl_mnth",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "prev_rdng_status",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("bl_mnth", models.CharField(blank=True, max_length=300, null=True)),
                ("rdng_date", models.CharField(blank=True, max_length=300, null=True)),
                ("geo_lat", models.CharField(blank=True, max_length=300, null=True)),
                ("geo_long", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "prsnt_mtr_status",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "abnormality",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("mr_rmrk", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "mtr_excep_img",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "rdng_ocr_status",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "prsnt_ocr_rdng",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("prsnt_rdng", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "prsnt_rdng_ocr_excep",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("rdng_img", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "ocr_md_status",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "prsnt_md_rdng_ocr",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "prsnt_md_rdng",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "md_ocr_excep",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("md_img", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "ocr_pf_status",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "ocr_pf_reading",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("pf_image", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "pf_manual_reading",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "pf_ocr_exception",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("ai_mdl_ver", models.CharField(blank=True, max_length=300, null=True)),
                ("ph_name", models.CharField(blank=True, max_length=300, null=True)),
                ("cmra_res", models.CharField(blank=True, max_length=300, null=True)),
                ("andr_ver", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "data_sync_date",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("qc_req", models.CharField(blank=True, max_length=300, null=True)),
                ("ba_cons_id", models.CharField(blank=True, max_length=300, null=True)),
                ("ba_ac_id", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "ba_prsnt_rdng_status",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("ba_mrc", models.CharField(blank=True, max_length=300, null=True)),
                ("ba_mru", models.CharField(blank=True, max_length=300, null=True)),
                ("ba_subdiv", models.CharField(blank=True, max_length=300, null=True)),
                ("ba_div", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "ba_geo_lati",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "ba_geo_long",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("ba_agnc_id", models.CharField(blank=True, max_length=300, null=True)),
                ("ba_bl_id", models.CharField(blank=True, max_length=300, null=True)),
                ("ba_bl_date", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "ba_prev_rdng_status",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("qc_done", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "qc_done_user_id",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("qc_date", models.CharField(blank=True, max_length=300, null=True)),
                ("qc_flag", models.CharField(blank=True, max_length=300, null=True)),
                ("qc_rmrk", models.CharField(blank=True, max_length=300, null=True)),
                ("ai_retrain", models.CharField(blank=True, max_length=300, null=True)),
                ("ocr_status", models.CharField(blank=True, max_length=300, null=True)),
                ("uploaded_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "abnormalities_confirm",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "ocrexception_confirm",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "qc_recommendation",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "qc_report_action",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("reading_date_db", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "readingmaster",
            },
        ),
        migrations.CreateModel(
            name="MeterReaderRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mrId", models.CharField(max_length=200, unique=True)),
                ("mrName", models.CharField(max_length=200)),
                ("section", models.CharField(max_length=200)),
                ("mrPhone", models.CharField(max_length=200)),
                ("mrPhoto", models.CharField(max_length=200)),
                ("androidToken", models.CharField(max_length=200)),
                ("uploaded_datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "meterreaderregistration",
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discom", models.CharField(max_length=200)),
                ("zone", models.CharField(max_length=200)),
                ("circlename", models.CharField(max_length=200)),
                ("divisionname", models.CharField(max_length=200)),
                ("divisioncode", models.CharField(max_length=200)),
                ("subdivision", models.CharField(max_length=200)),
                ("subdivisioncode", models.CharField(max_length=200)),
                ("sectionname", models.CharField(max_length=200)),
                ("sectioncode", models.CharField(max_length=200)),
                ("agency", models.CharField(blank=True, max_length=200, null=True)),
                ("agencycode", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "office",
            },
        ),
        migrations.CreateModel(
            name="UserManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email"
                    ),
                ),
                ("ofc_discom", models.CharField(blank=True, max_length=100, null=True)),
                ("ofc_zone", models.CharField(blank=True, max_length=100, null=True)),
                ("ofc_circle", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ofc_division",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ofc_subdivision",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ofc_section",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ofc_agency", models.CharField(blank=True, max_length=200, null=True)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("mobile_number", models.BigIntegerField()),
                (
                    "designation",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "profile_pic",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "usermanagement",
            },
        ),
    ]
