# Generated by Django 4.1.1 on 2023-01-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "notification_criteria",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "location_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "notification_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "message_image_url",
                    models.CharField(blank=True, max_length=350, null=True),
                ),
                (
                    "message_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "message_content",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "message_schedule_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Message_delivery_date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_time",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "notification_main",
            },
        ),
        migrations.CreateModel(
            name="notificatio_recepients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mr_id", models.CharField(blank=True, max_length=200, null=True)),
                ("mr_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "mr_token_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mr_mobile_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mr_location_section_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "message_image_url",
                    models.CharField(blank=True, max_length=350, null=True),
                ),
                (
                    "message_delivery_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "message_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "message_content",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("mr_agency", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "notification_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.notificationmani",
                    ),
                ),
            ],
            options={
                "db_table": "notification_recepients",
            },
        ),
    ]
