# Generated by Django 4.1.1 on 2023-01-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notificationmani_notificatio_recepients'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreaderregistration',
            name='circle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meterreaderregistration',
            name='discom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meterreaderregistration',
            name='division',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meterreaderregistration',
            name='subdivision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meterreaderregistration',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
