# Generated by Django 4.1.1 on 2023-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meterreaderregistration_circle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreaderregistration',
            name='androidToken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meterreaderregistration',
            name='mrName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meterreaderregistration',
            name='mrPhone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meterreaderregistration',
            name='mrPhoto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meterreaderregistration',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
