# Generated by Django 4.1.1 on 2023-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_meterreaderregistration_androidtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreaderregistration',
            name='sectioncode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
