# Generated by Django 4.1.1 on 2023-04-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_meterreaderregistration_sectioncode"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="qc_meter_status",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="consumers",
            name="qc_ocr_status",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
