# Generated by Django 4.1.1 on 2023-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_consumers_qc_meter_status_consumers_qc_ocr_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="manual_update_flag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
