# Generated by Django 4.1.1 on 2023-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_consumers_manual_update_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="prsnt_ocr_excep_old_values",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
