# Generated by Django 4.1.1 on 2023-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_consumers_prsnt_ocr_excep_old_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="is_object_meter",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="consumers",
            name="mr_success_feedback",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
