# Generated by Django 4.1.1 on 2023-05-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_consumers_is_object_meter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="md_reading_parameter_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="consumers",
            name="pf_reading_parameter_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="consumers",
            name="reading_parameter_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
