# Generated by Django 4.1.1 on 2023-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_consumers_md_reading_parameter_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="bill_month_dt",
            field=models.DateField(blank=True, null=True),
        ),
    ]
