# Generated by Django 4.1.1 on 2023-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_consumers_bill_month_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="prsnt_rdng_ocr_odv",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumers",
            name="rdng_ocr_status_changed_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumers",
            name="rdng_ocr_status_odv",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
