# Generated by Django 4.1.1 on 2023-06-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_consumers_prsnt_rdng_ocr_odv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="date_qc",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
