# Generated by Django 4.1.1 on 2023-06-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_consumers_prsnt_rdng_ocr_od_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumers",
            name="prsnt_rdng_ocr_od",
        ),
        migrations.RemoveField(
            model_name="consumers",
            name="rdng_ocr_status_changedby",
        ),
        migrations.RemoveField(
            model_name="consumers",
            name="rdng_ocr_status_od",
        ),
    ]
