# Generated by Django 4.1.1 on 2023-06-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_consumers_prsnt_rdng_ocr_od_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="prsnt_rdng_ocr_odv",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="consumers",
            name="rdng_ocr_status_changedby_v",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="consumers",
            name="rdng_ocr_status_odv",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
