# Generated by Django 4.1.1 on 2023-08-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_consumers_date_qc"),
        ("api", "0014_consumers_prsnt_rdng_ocr_odv_and_more"),
    ]

    operations = []
