# Generated by Django 4.1.1 on 2023-08-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_merge_20230808_1032"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumers",
            name="rdng_ocr_status_changedby_v",
        ),
    ]
