# Generated by Django 5.2.6 on 2025-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_consumers_rdng_ocr_status_changedby_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='kvah_rdng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consumers',
            name='kvak_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
