# Generated by Django 5.2.6 on 2025-09-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_consumers_kvah_rdng_consumers_kvak_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumers',
            old_name='kvak_img',
            new_name='kvah_img',
        ),
    ]
