# # Generated by Django 5.2.6 on 2025-09-18 17:15

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('api', '0018_rename_kvak_img_consumers_kvah_img'),
#     ]

#     operations = [
#     ]
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_rename_kvak_img_consumers_kvah_img"),
    ]

    operations = [
        # Adjust table name and types to your actual ones.
        migrations.RunSQL(
            "ALTER TABLE readingmaster ADD COLUMN IF NOT EXISTS kvah_rdng VARCHAR(255);",
            reverse_sql="ALTER TABLE readingmaster DROP COLUMN IF EXISTS kvah_rdng;"
        ),
        migrations.RunSQL(
            # Add kvah_img (example: VARCHAR(255) NULL if your model is CharField(max_length=255, null=True, blank=True))
            "ALTER TABLE readingmaster ADD COLUMN IF NOT EXISTS kvah_img VARCHAR(255);",
            reverse_sql="ALTER TABLE readingmaster DROP COLUMN IF EXISTS kvah_img;"
        ),
    ]
