# Generated by Django 5.2.6 on 2025-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fix_missing_cols'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
