# Generated by Django 5.2.6 on 2025-11-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_consumers_kvah_status_consumers_kvah_manual'),
        ('api', '0020_supervisorlogin'),
    ]

    operations = [
    ]
