# Generated by Django 5.2.6 on 2025-11-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20251119_1020'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supervisorlogin',
            table='supervisorlogin',
        ),
    ]
