# Generated by Django 5.2.6 on 2025-11-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_supervisorlogin_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorlogin',
            old_name='phone_number',
            new_name='supervisor_number',
        ),
    ]
