# Generated by Django 5.2.6 on 2025-11-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_phone_number_supervisorlogin_supervisor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorlogin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supervisorlogin',
            name='mr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisorlogin',
            name='mr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisorlogin',
            name='mr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisorlogin',
            name='ofc_division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisorlogin',
            name='ofc_subdivision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisorlogin',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
