# Generated by Django 5.2.6 on 2025-11-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_supervisorlogin_is_admin_supervisorlogin_mr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorlogin',
            name='supervisor_number',
            field=models.CharField(max_length=15),
        ),
    ]
