# Generated by Django 4.1.1 on 2025-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_supervisorlogin_supervisor_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="mtr_sr_no",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
