# Generated by Django 5.2 on 2025-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_consumers_mtr_sr_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervsiorLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supervisor_number', models.CharField(max_length=15)),
                ('geo_lat', models.CharField(blank=True, max_length=300, null=True)),
                ('geo_long', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supervsiorlocation',
            },
        ),
    ]
