# Generated by Django 5.2 on 2025-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_supervsiorlocation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supervsiorlocation',
            constraint=models.UniqueConstraint(fields=('supervisor_number', 'date'), name='unique_supervisor_date'),
        ),
    ]
