# Generated by Django 5.2.6 on 2026-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_supervsiorlocation_unique_supervisor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorlogin',
            name='discom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
