# Generated by Django 5.2.6 on 2026-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_supervisorlogin_discom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supervisor_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('meta', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'supervisor_location',
            },
        ),
        migrations.DeleteModel(
            name='SupervsiorLocation',
        ),
        migrations.AddConstraint(
            model_name='supervisorlocation',
            constraint=models.UniqueConstraint(fields=('supervisor_number', 'date'), name='unique_supervisor_per_day'),
        ),
    ]
