# Generated by Django 5.2.6 on 2026-01-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_supervisorlocation_delete_supervsiorlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervsiorLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supervisor_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'supervsiorlocation',
            },
        ),
        migrations.DeleteModel(
            name='SupervisorLocation',
        ),
        migrations.AddConstraint(
            model_name='supervsiorlocation',
            constraint=models.UniqueConstraint(fields=('supervisor_number', 'date'), name='unique_supervisor_date'),
        ),
    ]
